### ISSUE TITLE
when run layout cast in android studio tool bar,it can't work,this is log.mac os and android 5.1.1

### ISSUE THREAD

**Issue by forzajuve** [mmin18/LayoutCast#17]
Traceback (most recent call last):
File "/var/folders/8n/x_crp1rx3z9dmlphr2bndl_80000gn/T/lcast55613124027164810821.50808", line 417, in 
projlist = [i for i in list_projects(dir) if is_launchable_project(i)]
File "/var/folders/8n/x_crp1rx3z9dmlphr2bndl_80000gn/T/lcast55613124027164810821.50808", line 254, in list_projects
if package_name(cdir):
File "/var/folders/8n/x_crp1rx3z9dmlphr2bndl_80000gn/T/lcast55613124027164810821.50808", line 127, in package_name
data = manifestfile.read()
File "/System/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 489: ordinal not in range(128)

**Comment by mmin18** [comment]
should be fixed in the latest cast.py file, can you try to execute that on terminal?
