### ISSUE TITLE
fail to override resource in context 

### ISSUE THREAD

**Issue by ASCE1885** [mmin18/LayoutCast#53]
09-08 17:44:55.425  26516-26516/com.pyt.any E/lcast﹕ fail to override resource in context com.pyt.any.hybrid.activity.MyActivity@42fb4420
    java.lang.NoSuchFieldException: mResources
            at java.lang.Class.getDeclaredField(Class.java:631)
            at com.github.mmin18.layoutcast.context.OverrideContext.override(OverrideContext.java:82)
            at com.github.mmin18.layoutcast.context.OverrideContext.overrideDefault(OverrideContext.java:251)
            at com.github.mmin18.layoutcast.inflater.BootInflater.cloneInContext(BootInflater.java:36)
            at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:75)
            at android.app.Activity.getSystemService(Activity.java:4498)
            at android.view.LayoutInflater.from(LayoutInflater.java:275)
            at com.android.internal.policy.impl.PhoneWindow.<init>(PhoneWindow.java:282)
            at com.android.internal.policy.impl.Policy.makeNewWindow(Policy.java:65)
            at com.android.internal.policy.PolicyManager.makeNewWindow(PolicyManager.java:59)
            at android.app.Activity.attach(Activity.java:5047)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2041)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
            at android.app.ActivityThread.access$600(ActivityThread.java:140)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4914)
            at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by mmin18** [comment]
Which phone and android system version are you using?

**Comment by ASCE1885** [comment]
Mi 2S
Android 4.1.1
