### ISSUE TITLE
window Androidstudio1.4 errors

### ISSUE THREAD

**Issue by looooker** [mmin18/LayoutCast#71]
it shows the follows ,once  I  click the LayoutCast button it shows this 

Traceback (most recent call last): File "C:\Users\master\.AndroidStudio1.4\system\tmp\lcast50666631302600571711.50922", line 634, in   pnlist = [package_name_fromapk(i,sdkdir) for i in projlist] File "C:\Users\master\.AndroidStudio1.4\system\tmp\lcast50666631302600571711.50922", line 634, in   pnlist = [package_name_fromapk(i,sdkdir) for i in projlist] File "C:\Users\master\.AndroidStudio1.4\system\tmp\lcast50666631302600571711.50922", line 192, in package_name_fromapk aaptpath = get_aapt(sdkdir) File "C:\Users\master\.AndroidStudio1.4\system\tmp\lcast50666631302600571711.50922", line 423, in get_aapt if LooseVersion(pn) > minv: File "C:\Python34\lib\distutils\version.py", line 70, in __gt__ c = self._cmp(other) File "C:\Python34\lib\distutils\version.py", line 343, in _cmp if self.version other.version: TypeError: unorderable types: str() int()

**Comment by lingfengxu** [comment]
我这也报同样的错误

**Comment by weiguo0535** [comment]
this is a very good tools, but my windows has the same program，please solve it，thanks
android studio version 1.4
android phone version 5.1
